plugin.plugin_configuration.external_entities_storage_client.external_rss:
  type: config_object
  label: 'External entities Rss storage client settings'
  mapping:
    endpoint:
      type: string
      label: 'Endpoint'
    item_map_key:
      type: string
      label: 'Item map key'
    pager:
      type: mapping
      label: 'Pager'
      mapping:
        default_limit:
          type: integer
          label: 'Default limit'
    cron:
      type: mapping
      label: 'Cron'
      mapping:
        cron_restore:
          type: boolean
          label: 'Cron restore'
        cron_restore_interval:
          type: integer
          label: 'Cron restore interval'
    email:
      type: mapping
      label: 'Email'
      mapping:
        send:
          type: string
          label: 'Send email'
        template:
          type: string
          label: 'Email template'
